version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  service-ai:
    build:
      context: ./AI-chat-backend
      dockerfile: Dockerfile
    ports:
      - "8000-8800:8000"
    env_file:
      - ./AI-chat-backend/.env
    depends_on:
      - proxy