version: '3.8'

services:
  service-ai:
    image: service-ai:latest
    ports:
      - "8000-8800:8000"
    env_file:
      - ./AI-chat-backend/.env
  proxy:
    image: backend-proxy:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8888:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
